name: Build and Test Shopping App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 16.x
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
        cache: 'npm'
    - name: install npm dependencies
      run: npm install
    - name: run unit tests
      run: npm run test:unit
    - name: display softuni username
      run: echo "AneVG"

  ui_test:
    needs: build-test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 16.x
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
        cache: 'npm'
    - name: install npm dependencies
      run: npm install
    - name: install playwright dependencies
      run: npx playwright install
    - name: install express
      run: npm install express
    - name: start the app
      run: npm start
    - name: run ui tests
      run: npm run test:ui

 
